<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>BotBanter</AssemblyName>
    <RootNamespace>BotBanter</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.367" />
  </ItemGroup>

  <ItemGroup>
    <None Include="lines\**\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
